#!/usr/bin/env node
/**
 * Build a static `public/` tree for Vercel.
 *
 * Layout served at the site root:
 *   /              → app/index.html
 *   /app/*         → app/*
 *   /data/*        → data/*
 *   /cjs/*         → .old/cjs/*
 *   /vyuka_downloaded/* → .old/vyuka_downloaded/*
 *
 * Run: node tools/prepare_vercel.mjs
 */

import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const PUB = join(ROOT, "public");

function mustExist(rel) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) {
    console.error(`Missing required path: ${rel}`);
    process.exit(1);
  }
  return p;
}

function copyDir(srcRel, destRel) {
  const src = mustExist(srcRel);
  const dest = join(PUB, destRel);
  mkdirSync(dest, { recursive: true });
  cpSync(src, dest, { recursive: true });
  console.log(`  ✓ ${srcRel} → public/${destRel}`);
}

function countFiles(dir) {
  let n = 0;
  const walk = (d) => {
    try {
      for (const name of readdirSync(d)) {
        const p = join(d, name);
        try {
          if (statSync(p).isDirectory()) walk(p);
          else n++;
        } catch {
          // ignore broken symlink / missing target
        }
      }
    } catch {
      // ignore unreadable directory
    }
  };
  if (existsSync(dir)) walk(dir);
  return n;
}

function optionalCopyDir(srcRel, destRel) {
  const src = join(ROOT, srcRel);
  const dest = join(PUB, destRel);
  if (existsSync(src)) {
    mkdirSync(dest, { recursive: true });
    cpSync(src, dest, { recursive: true });
    console.log(`  ✓ ${srcRel} → public/${destRel}`);
  } else {
    console.log(`  - ${srcRel} not present (preserving prebuilt public/${destRel})`);
  }
}

console.log("Preparing public/ for Vercel …");

mkdirSync(PUB, { recursive: true });

copyDir("app", "app");
copyDir("data", "data");
optionalCopyDir(join(".old", "cjs"), "cjs");
optionalCopyDir(join(".old", "vyuka_downloaded"), "vyuka_downloaded");
optionalCopyDir("cjs", "cjs");
optionalCopyDir("vyuka_downloaded", "vyuka_downloaded");

// Root index so `/` works without rewrites (rewrites still set as backup)
if (existsSync(join(PUB, "app", "index.html"))) {
  cpSync(join(PUB, "app", "index.html"), join(PUB, "index.html"));
  console.log("  ✓ app/index.html → public/index.html");
}

// Favicon if present
const fav = join(PUB, "app", "favicon.ico");
if (existsSync(fav)) {
  cpSync(fav, join(PUB, "favicon.ico"));
}

// Lightweight deploy stamp (debug)
writeFileSync(
  join(PUB, "deploy.json"),
  JSON.stringify(
    {
      builtAt: new Date().toISOString(),
      files: countFiles(PUB),
      note: "Generated by tools/prepare_vercel.mjs — do not edit",
    },
    null,
    2,
  ) + "\n",
  "utf8",
);

console.log(`Done. public/ has ${countFiles(PUB)} files.`);
console.log(`Output: ${relative(ROOT, PUB) || "public"}`);
